name: Post welcome content
on: 
  pull_request:
    types: [opened]
permissions:
pull_requests: write
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welocome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB.TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      
